# 백엔드 CI/CD 파이프라인 워크플로우
name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'  # 백엔드 코드가 변경될 때
      - '.github/workflows/backend.yml'  # 백엔드 워크플로우 파일이 변경될 때
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'  # 백엔드 워크플로우 파일이 변경될 때

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # JDK 21 설정
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'oracle'
        cache: maven
    
    # 백엔드 빌드
    - name: Build Backend
      working-directory: ./backend  # 이 스텝은 backend 디렉토리에서 실행
      run: mvn compile  # 직접 mvn 명령어 사용
    
    # 백엔드 테스트 실행
    - name: Test Backend
      working-directory: ./backend  # 이 스텝은 backend 디렉토리에서 실행
      run: mvn test
    
    # 백엔드 패키지 생성 (JAR 파일)
    - name: Package Backend
      working-directory: ./backend  # 이 스텝은 backend 디렉토리에서 실행
      run: mvn package -Dmaven.test.skip
    
    # Docker 빌드 환경 설정
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Docker Hub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    # 백엔드 이미지 빌드 및 Docker Hub에 푸시
    - name: Build and push Backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend  # 백엔드 디렉토리 경로
        file: ./backend/Dockerfile  # 백엔드 Dockerfile 경로
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest