# 프론트엔드 CI/CD 파이프라인 워크플로우
name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'  # 프론트엔드 코드가 변경될 때만 실행
      - '.github/workflows/frontend.yml'  # 프론트엔드 워크플로우 파일이 변경될 때
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'  # 프론트엔드 워크플로우 파일이 변경될 때

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    # 프론트엔드 의존성 설치
    - name: Install Frontend Dependencies
      run: |
        cd frontend  # 프론트엔드 디렉토리로 이동
        npm install
    
    # 프론트엔드 빌드
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
    
    # Docker 빌드 환경 설정
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    # Docker Hub 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    # 프론트엔드 이미지 빌드 및 Docker Hub에 푸시
    - name: Build and push Frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend  # 프론트엔드 디렉토리 경로
        file: ./frontend/Dockerfile  # 프론트엔드 Dockerfile 경로
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest